services:
  frontend:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_IIIF_UPSTREAM: ${NEXT_PUBLIC_IIIF_UPSTREAM}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
        DOCKER_IMAGE_HASH: ${DOCKER_IMAGE_HASH}

    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_IIIF_UPSTREAM: ${NEXT_PUBLIC_IIIF_UPSTREAM}
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DOCKER_IMAGE_HASH: ${DOCKER_IMAGE_HASH}
